apiVersion: apps/v1
kind: Deployment
metadata:
  name: author-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: author-service
  template:
    metadata:
      labels:
        app: author-service
    spec:
      containers:
        - name: author-service
          image: apicomp-lab/author-service:v1.0.0
          ports:
            - containerPort: 8080
          imagePullPolicy: Never
          env:
            - name: SERVICE_NAME
              value: author-service
