kind: Service
apiVersion: v1
metadata:
  name: inventory-service
spec:
  selector:
    app: inventory-service
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 8080
  type: ClusterIP
